name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "src/dist/windows/FFXIV-Afk-Bot.exe"
        asset_name: "FFXIV-Afk-Bot.exe"
        tag: V.${{ github.run_number }}.0
        overwrite: true
        body: ${{ github.event.commits[0].message }}
